config/routes.rb
Rails.application.routes.draw do

  get 'home/show'

  resources :text_pages
  resources :images
  resources :galleries
  resources :sessions, only: :create
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get ':url', to: 'text_pages#show', as: 'specific_text_page'

  root to: 'home#show'

end

app/models/text_page.rb
class TextPage < ActiveRecord::Base
end

app/controllers/text_pages_controller.rb
class TextPagesController < ApplicationController
  skip_before_action :authorize, only: :show
  before_action :set_text_page, only: [:show, :edit, :update, :destroy]
  before_action :set_title, only: :show

  # GET /text_pages
  # GET /text_pages.json
  def index
    @text_pages = TextPage.all
  end

  # GET /text_pages/1
  # GET /text_pages/1.json
  def show
  end

  # GET /text_pages/new
  def new
    @text_page = TextPage.new
  end

  # GET /text_pages/1/edit
  def edit
  end

  # POST /text_pages
  # POST /text_pages.json
  def create
    @text_page = TextPage.new(text_page_params)

    respond_to do |format|
      if @text_page.save
        format.html { redirect_to @text_page, notice: 'Text page was successfully created.' }
        format.json { render :show, status: :created, location: @text_page }
      else
        format.html { render :new }
        format.json { render json: @text_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_pages/1
  # PATCH/PUT /text_pages/1.json
  def update
    respond_to do |format|
      if @text_page.update(text_page_params)
        format.html { redirect_to @text_page, notice: 'Text page was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_page }
      else
        format.html { render :edit }
        format.json { render json: @text_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_pages/1
  # DELETE /text_pages/1.json
  def destroy
    @text_page.destroy
    respond_to do |format|
      format.html { redirect_to text_pages_url, notice: 'Text page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_page
      if current_user.blank?
        @text_page = TextPage.where('active = ?', true)
      else
        @text_page = TextPage
      end

      if params[:url].present?
        @text_page = @text_page.find_by_url(params[:url])
      else params[:id] && current_user.blank?
        @text_page = @text_page.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_page_params
      params.require(:text_page)
        .permit(:title, :body, :active, :show_in_menu, :url, :priority)
    end

    def set_title
      @title = "#{@text_page.title} | #{super}"
    end
end

app/helpers/text_pages_helper.rb
module TextPagesHelper
end

app/views/text_pages/_form.html.erb
<%= form_for(@text_page) do |f| %>
  <% if @text_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_page.errors.count, "error") %> prohibited this text_page from being saved:</h2>

      <ul>
      <% @text_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 30, cols: 100 %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :show_in_menu %><br>
    <%= f.check_box :show_in_menu %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.text_field :priority %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_pages/edit.html.erb
<h1>Editing text_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_page %> |
<%= link_to 'Back', text_pages_path %>

app/views/text_pages/index.html.erb
<h1>Listing text_pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>URL</th>
      <th>Body</th>
      <th>Active</th>
      <th>Show in menu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @text_pages.each do |text_page| %>
      <tr>
        <td><%= text_page.title %></td>
        <td><%= text_page.url %></td>
        <td><%= text_page.body %></td>
        <td><%= text_page.active %></td>
        <td><%= text_page.show_in_menu %></td>
        <td><%= link_to 'Show', text_page %></td>
        <td><%= link_to 'Edit', edit_text_page_path(text_page) %></td>
        <td><%= link_to 'Destroy', text_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text page', new_text_page_path %>

app/views/text_pages/new.html.erb
<h1>New text_page</h1>

<%= render 'form' %>

<%= link_to 'Back', text_pages_path %>

app/views/text_pages/show.html.erb
<% if current_user.present? && notice.present? %>
  <p id="notice"><%= notice %></p>
<% end %>

<nav id="text_page_navigation" class="mt15em">
  <h2><%= @text_page.title %></h2>
</nav>

<p><%= @text_page.body.html_safe %></p>

<% if current_user.present? %>
  <%= link_to 'Edit', edit_text_page_path(@text_page) %> |
  <%= link_to 'Back', text_pages_path %>
<% end %>