config/routes.rb
Rails.application.routes.draw do

  get 'home/show'

  resources :text_pages
  resources :images
  resources :galleries
  resources :sessions, only: :create
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get ':url', to: 'text_pages#show', as: 'specific_text_page'

  root to: 'home#show'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images

  validates_presence_of :title
  validates_presence_of :url
  validates_uniqueness_of :url

  def images_to_json
    list =  []
    images.order(:priority, :id).each do |image|
      item = "title: \"#{image.title}\", "
      item += "description: \"#{image.description}\", "
      item += "url: \"#{image.image.url(:large)}\""
      list << "{ " + item + " }"
    end
    list.join(",")
  end

  def to_param
    url
  end

  def self.by_priority
    order("priority")
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]
  before_action :set_title, except: [:index, :destroy]
  skip_before_action :authorize, only: :show

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find_by_url(params[:id])
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_title
      title = "#{@gallery.title} | " if @gallery.present?
      @title = "#{title}#{super}"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find_by_url(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:title, :url, :description, :priority)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.text_field :priority %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.title %></td>
        <td><%= gallery.description %></td>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<% if current_user.present? && notice.present? %>
  <p id="notice"><%= notice %></p>
<% end %>

<nav id="gallery_navigation" class="mt15em">
  <h2><%= @gallery.title %></h2>
  <a href="#" id="arrow_left"><span>previous photo</span></a>
  <a href="#" id="arrow_right"><span>next photo</span></a>
  <div class="cleaner"></div>
</nav>

<% if @gallery.description.present? %>
  <p><%= @gallery.description %></p>
<% end %>

<% @gallery.images.order(:priority, :id).each do |image| %>
  <%= image_tag image.image.url(:large), alt: image.title_and_description, data: { order: 0 } %>
  <% if image.title_and_description.present? %>
    <p><%= image.title_and_description %></p>
  <% end %>
<% end %>

<% if current_user.present? %>
  <%= link_to 'Edit', edit_gallery_path(@gallery) %> |
  <%= link_to 'Back', galleries_path %>
<% end %>

<script>
var gallery_images = [
  <%= @gallery.images_to_json.html_safe %>
];

</script>