config/routes.rb
Rails.application.routes.draw do

  get 'home/show'

  resources :text_pages
  resources :images
  resources :galleries
  resources :sessions, only: :create
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get ':url', to: 'text_pages#show', as: 'specific_text_page'

  root to: 'home#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_main_menu
  before_action :set_title
  before_action :current_user
  before_action :authorize

  protected

  def set_title
    @title = "adam vasicek photographs"
  end

  private

  def set_main_menu
    @main_menu = {}

    @main_menu[:galleries] = []
    Gallery.by_priority.each do |gallery|
      @main_menu[:galleries] << { title: gallery.title, url: gallery_url(gallery) }
    end

    @main_menu[:text_pages] = []
    TextPage.where('show_in_menu = ?', true).order(:priority).each do |text_page|
      @main_menu[:text_pages] << {
        title: text_page.title, url: specific_text_page_url(text_page.url)
      }
    end

    @main_menu
  end

  def current_user
    @current_user = @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end
  helper_method :current_user

  def authorize
    redirect_to root_url, notice: "please log in" if current_user.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_main_menu.html.erb
<ul class="main_menu">
  <li><span class="bold">GALLERIES</span>
    <ul>
      <% @main_menu[:galleries].each do |menu_item| %>
        <% if current_page? menu_item[:url] %>
          <li id="current"><%= menu_item[:title] %></li>
        <% else %>
          <li><%= link_to menu_item[:title], menu_item[:url] %></li>
        <% end %>
      <% end %>
    </ul>
  </li>
</ul>
<ul class="main_menu">
  <li><span class="bold">INFO</span>
    <ul>
      <% @main_menu[:text_pages].each do |menu_item| %>
        <% if current_page? menu_item[:url] %>
          <li id="current"><%= menu_item[:title] %></li>
        <% else %>
          <li><%= link_to menu_item[:title], menu_item[:url] %></li>
        <% end %>
      <% end %>
    </ul>
  </li>
</ul>

app/views/application/_user_menu.html.erb
<% if current_user.present? %>
  <ul id="user_menu">
    <li><%= link_to 'galleries', galleries_url %></li>
    <li><%= link_to 'images', images_url %></li>
    <li><%= link_to 'text pages', text_pages_url %></li>
    <li><%= link_to "logout", logout_url, method: :delete %>
  </ul>
<% end %>