config/routes.rb
Rails.application.routes.draw do

  get 'home/show'

  resources :text_pages
  resources :images
  resources :galleries
  resources :sessions, only: :create
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get ':url', to: 'text_pages#show', as: 'specific_text_page'

  root to: 'home#show'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery

  has_attached_file :image,
    styles: { large: '800x500>', thumb: '200x200'},
    storage: :dropbox,
    dropbox_credentials: Rails.root.join('config/dropbox.yml'),
    dropbox_visibility: 'public',
    url: '/Public/websites/portfolio/:id_:basename_:style.:extension',
    path: '/Public/websites/portfolio/:id_:basename_:style.:extension'

  validates_attachment_content_type :image, { content_type: ['image/jpeg', 'image/png'] }
  validates_attachment_file_name :image, matches: [/pngZ/, /jpe?g\Z/]
  validates_attachment_presence :image

  def title_and_description
    if title.present? && description.present?
      "#{title}: #{description}"
    elsif title.present?
      title
    elsif description.present?
      description
    else
      ''
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :set_galleries, only: [:new, :create, :edit, :update]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all.order(:gallery_id, :priority, :id)
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to images_url, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to images_url, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    def set_galleries
      @galleries = []
      Gallery.all.each {|gallery| @galleries << [gallery.title, gallery.id]}
      @galleries
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image)
        .permit(:title, :description, :image, :gallery_id, :active,
          :show_on_homepage, :priority)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gallery_id %><br>
    <%= f.select :gallery_id, options_for_select(@galleries, @image.gallery_id) %>
  </div>
  <div class="field">
    <% if @image.image.present? %>
      <%= image_tag @image.image.url(:thumb) %><br>
    <% end %>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.check_box :active %>
    <%= f.label :active %><br>
  </div>
  <div class="field">
    <%= f.check_box :show_on_homepage %>
    <%= f.label :show_on_homepage %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>
<%= link_to 'New Image', new_image_path %>

<ul id="images_list">
  <% @images.each_with_index do |image, index| %>
    <li>
      <div>
        <%= image_tag image.image.url(:thumb), alt: image.title_and_description %>
        <%= link_to 'Show', image %>&nbsp;
        <%= link_to 'Edit', edit_image_path(image) %>&nbsp;
        <%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </li>

  <% end %>
</ul>
<br>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<div id="image_metadata">
  <strong>Gallery:</strong>&nbsp;<%= @image.gallery.title %>
  <br>
  <strong>Priority:</strong>&nbsp;<%= @image.priority %>
  <br>
  <strong>Title:</strong>&nbsp;<%= @image.title || 'untitled' %>
  <br>
  <strong>Description:</strong>&nbsp;<%= @image.description %>
  <br>
  <strong>Active:</strong>&nbsp;<%= @image.active ? 'yes' : 'no' %>
  <br>
  <strong>Show on homepage:</strong>&nbsp;<%= @image.show_on_homepage ? 'yes' : 'no' %>
</div>

<div id="image_large">
  <%= image_tag @image.image.url(:large) %>
</div>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>